//ACTIONS FOR USERS

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

//ACTIONS FOR PLACES

export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const GET_PLACES_FAILURE = "GET_PLACES_FAILURE";

export const GET_SINGLE_PLACE_SUCCESS = "GET_SINGLE_PLACE_SUCCESS";
export const GET_SINGLE_PLACE_FAILURE = "GET_SINGLE_PLACE_FAILURE";

export const ADD_PLACE_SUCCESS = "ADD_PLACE_SUCCESS";
export const ADD_PLACE_FAILURE = "ADD_PLACE_FAILURE";

export const ADD_PLACE_IMAGE_SUCCESS = "ADD_PLACE_SUCCESS";
export const ADD_PLACE_IMAGE_FAILURE = "ADD_PLACE_FAILURE";

export const ADD_PLACE_REVIEW_SUCCESS = "ADD_PLACE_REVIEW_SUCCESS";
export const ADD_PLACE_REVIEW_FAILURE = "ADD_PLACE_REVIEW_FAILURE";

//ACTIONS FOR ADMIN

export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
export const DELETE_PLACE_FAILURE =  "DELETE_PLACE_FAILURE";